import { NextResponse } from 'next/server';

export async function GET() {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Meeting Intelligence Agent - Summary Report</title>
      <style>
        body { font-family: Helvetica, Arial, sans-serif; margin: 40px; color: #0f172a; }
        h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
        .meta { background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; margin-bottom: 20px; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-size: 13px; }
        th { background: #eef2ff; color: #3730a3; }
        .badge { background: #dcfce7; color: #166534; padding: 3px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>Meeting Intelligence Agent</h1>
      <p style="color: #64748b; font-size: 13px;">Single Deployment Full-Stack Summary Report &bull; Hosted on Vercel</p>
      
      <div class="meta">
        <p><strong>Meeting Name:</strong> Weekly Product & Engineering Sync</p>
        <p><strong>Date:</strong> September 10, 2026</p>
        <p><strong>Participants:</strong> Alex Chen, Maya Lin, Marcus Vance</p>
        <p><strong>Status:</strong> <span class="badge">✓ Verified & Synced in Linear</span></p>
      </div>

      <h3>Extracted & Verified Action Items</h3>
      <table>
        <thead>
          <tr>
            <th>Task Description</th>
            <th>Person Responsible</th>
            <th>Due Date</th>
            <th>Linear Ticket ID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Configure database search index for fast retrieval</td>
            <td><strong>Marcus</strong></td>
            <td>2026-09-12</td>
            <td><strong style="color: #7c3aed;">LIN-2041</strong></td>
          </tr>
          <tr>
            <td>Complete 6-stage closed loop state machine</td>
            <td><strong>Maya</strong></td>
            <td>2026-09-10</td>
            <td><strong style="color: #7c3aed;">LIN-2042</strong></td>
          </tr>
        </tbody>
      </table>

      <footer style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 12px; color: #94a3b8;">
        Generated by Meeting Intelligence Agent &bull; Unified Single Deployment on Vercel
      </footer>
    </body>
    </html>
  `;

  return new NextResponse(htmlContent, {
    headers: {
      'Content-Type': 'text/html',
    },
  });
}
